name: "run brokers and trackers"
description: "run brokers and trackers directly from the monorepo codebase"

runs:
  using: "composite"
  steps:
    - name: run brokers and trackers
      run: |
        mkdir -p logs
        (cd packages/broker/dist/bin && node run-all.js) >logs/broker-tracker-logs.txt 2>&1 &
      shell: bash
      working-directory: './'
