name: build

on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - '*'
concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: package-lock.json
          check-latest: true
      - name: bootstrap
        run: npm run bootstrap
      - name: check
        run: npm run check
      - name: eslint
        run: npm run eslint
      - name: cache build
        uses: actions/cache@v3
        env:
          cache-name: cache-build
        with:
          path: |
            node_modules
            packages/broker/node_modules
            packages/cli-tools/node_modules
            packages/client/node_modules
            packages/network/node_modules
            packages/network-tracker/node_modules
            packages/protocol/node_modules
            packages/test-utils/node_modules
            packages/utils/node_modules
            packages/broker/dist
            packages/cli-tools/dist
            packages/client/dist
            packages/network/dist
            packages/network-tracker/dist
            packages/protocol/dist
            packages/test-utils/dist
            packages/utils/dist
          key: cache-build-${{ github.head_ref }}
  test-utils:
    needs: [build]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test-utils
    steps:
      - name: test
        run: npm run test
