name: build

on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - '*'
concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: ./reusable/cached-build
      - name: versions
        run: npm run versions
      - name: check
        run: npm run check
      - name: eslint
        run: npm run eslint
  test-utils:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: ./reusable/cached-build
      - name: test
        working-directory: 'packages/test-utils'
        run: npm run test
