name: build

on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - '*'
concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        uses: ./.github/workflows/reusable/cached-build
      - name: versions
        run: npm run versions
      - name: check
        run: npm run check
      - name: eslint
        run: npm run eslint
  test:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [test-utils, utils, protocol, network, tracker]
    steps:
      - uses: actions/checkout@v3
      - name: build (cached)
        uses: ./.github/workflows/reusable/cached-build
      - name: test
        working-directory: 'packages/${{matrix.package}}'
        run: npm run test
