name: build

on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - '*'
concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: package-lock.json
          check-latest: true
      - name: cache build
        uses: actions/cache@v3
        env:
          cache-name: cache-build
        with:
          path: |
            node_modules
            packages/*/node_modules
            packages/*/dist
          key: cache-build-${{ github.sha }}
      - name: ci
        run: npm ci --no-audit
      - name: versions
        run: npm run versions
      - name: build
        run: npm run build
      - name: check
        run: npm run check
      - name: eslint
        run: npm run eslint
  test-utils:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: cache build
        uses: actions/cache@v3
        env:
          cache-name: cache-build
        with:
          path: |
            node_modules
            packages/*/node_modules
            packages/*/dist
          key: cache-build-${{ github.sha }}
      - name: test
        run: npm run test --workspace=test-utils
  utils:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: cache build
        uses: actions/cache@v3
        env:
          cache-name: cache-build
        with:
          path: |
            node_modules
            packages/*/node_modules
            packages/*/dist
          key: cache-build-${{ github.sha }}
      - name: test
        run: npm run test --workspace=utils
