# Any tests that can run without building should go in here.
name: Client – Lint, Unit, Integration Tests

# Be sure to update both workflow files if you edit any env or trigger config
env:
  CI: true
  DEBUG_COLORS: true
  DEBUG: "Streamr*"
on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - '*'
  schedule:
    # run every day at 00:00
    - cron:  '0 0 * * *'

defaults:
  run:
    working-directory: packages/client

jobs:
  test:
    name: Test Unit using Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    env:
      TEST_REPEATS: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-${{ matrix.node-version }}
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: npm ci
        working-directory: './'
        run: |
          npm ci
          npx lerna bootstrap --scope streamr-client --include-dependencies
      - timeout-minutes: 2
        continue-on-error: true
        run: npx jest --detectOpenHandles test/unit/AggregatedError.test.ts
      - timeout-minutes: 2
        continue-on-error: true
        run: npx jest --detectOpenHandles test/unit/Encryption.test.ts
      - timeout-minutes: 2
        continue-on-error: true
        run: npx jest --detectOpenHandles test/unit/iterators.test.js
      - timeout-minutes: 2
        continue-on-error: true
        run: npx jest --detectOpenHandles test/unit/MessageCreator.test.ts
      - timeout-minutes: 2
        continue-on-error: true
        run: npx jest --detectOpenHandles test/unit/PushQueue.test.js
      - timeout-minutes: 2
        continue-on-error: true
        run: npx jest --detectOpenHandles test/unit/pUtils.test.js
      - timeout-minutes: 2
        continue-on-error: true
        run: npx jest --detectOpenHandles test/unit/Scaffold.test.ts
      - timeout-minutes: 2
        continue-on-error: true
        run: npx jest --detectOpenHandles test/unit/Session.test.ts
      - timeout-minutes: 2
        continue-on-error: true
        run: npx jest --detectOpenHandles test/unit/Signer.test.ts
      - timeout-minutes: 2
        continue-on-error: true
        run: npx jest --detectOpenHandles test/unit/Stream.test.ts
      - timeout-minutes: 2
        continue-on-error: true
        run: npx jest --detectOpenHandles test/unit/StreamUtils.test.ts
      - timeout-minutes: 2
        continue-on-error: true
        run: npx jest --detectOpenHandles test/unit/utils.test.ts
      - timeout-minutes: 2
        continue-on-error: true
        run: npx jest --detectOpenHandles test/unit/GroupKeyStore.test.ts
      - timeout-minutes: 2
        continue-on-error: true
        run: npx jest --detectOpenHandles test/unit/GroupKeyPersistence.test.ts
      - timeout-minutes: 2
        continue-on-error: true
        run: npx jest --detectOpenHandles test/unit/Connection.test.ts
