---
# Any tests that can run without building should go in here.
name: Client – Lint, Unit, Integration Tests

# Be sure to update both workflow files if you edit any env or trigger config
env:
  CI: true
  DEBUG_COLORS: true
  DEBUG: "Streamr*"
on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - '*'
concurrency:
  group: client-code-build-${{ github.head_ref }}
  cancel-in-progress: true
defaults:
  run:
    working-directory: packages/client

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.5.1
        with:
          cache: 'npm'
          cache-dependency-path: package-lock.json
          node-version-file: '.nvmrc'
      - name: bootstrap-pkg
        working-directory: './'
        run: |
          npm install -g npm@8 --prefer-offline --no-audit
          npm run bootstrap-pkg streamr-client
      - run: npm run eslint

  test:
    name: Test Unit using Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    env:
      TEST_REPEATS: 1
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: package-lock.json
          cache: 'npm'
          check-latest: true
      - name: bootstrap-pkg
        working-directory: './'
        run: |
          npm install -g npm@8 --prefer-offline --no-audit
          npm run bootstrap-pkg streamr-client
      - name: test-unit
        timeout-minutes: 7
        run: npm run test-unit

  integration:
    name: ${{ matrix.test-name }} using Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
        test-name: [
          "test-integration-no-resend",
          "test-integration-resend",
        ]
    env:
      TEST_NAME: ${{ matrix.test-name }}
      TEST_REPEATS: 1

    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: package-lock.json
          cache: 'npm'
          check-latest: true
      - name: bootstrap-pkg
        working-directory: './'
        run: |
          npm install -g npm@8 --prefer-offline --no-audit
          npm run bootstrap-pkg streamr-client
      - name: Start Streamr Docker Stack
        uses: streamr-dev/streamr-docker-dev-action@v1.0.0-alpha.3
        with:
          services-to-start: "mysql redis core-api cassandra parity-node0 parity-sidechain-node0 bridge nginx smtp graph-deploy-streamregistry-subgraph chainlink"
      - name: start trackers and brokers
        uses: ./.github/workflows/reusable/run-brokers-and-trackers
      - name: Run Test
        run: npm run $TEST_NAME
      - name: Collect docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2.0.2
        with:
          dest: 'logs'
      - name: Upload logs to GitHub
        if: failure()
        uses: actions/upload-artifact@v2.3.1
        with:
          name: docker-logs-${{ matrix.test-name }}-node${{ matrix.node-version }}--${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt}}
          path: 'logs'
      - name: Stop Streamr Docker Stack
        if: always()
        run: |
          docker kill $(docker ps -q)
          docker rm $(docker ps -a -q)

  flakey:
    if: ${{ false }}
    name: Flakey Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.5.1
        with:
          cache-dependency-path: package-lock.json
          cache: 'npm'
          node-version-file: '.nvmrc'
      - name: bootstrap-pkg
        working-directory: './'
        run: |
          npm install -g npm@8 --prefer-offline --no-audit
          npm run bootstrap-pkg streamr-client
      - name: Start Streamr Docker Stack
        uses: streamr-dev/streamr-docker-dev-action@v1.0.0-alpha.3
        with:
          services-to-start: "mysql redis core-api cassandra parity-node0 parity-sidechain-node0 bridge nginx smtp graph-deploy-streamregistry-subgraph"
      - name: start trackers and brokers
        uses: ./.github/workflows/reusable/run-brokers-and-trackers
      - uses: nick-invision/retry@v2
        name: Run Test
        with:
          max_attempts: 2
          timeout_minutes: 15
          retry_on: error
          command: cd packages/client && npm run test-flakey || echo "::warning::Flakey Tests Failed"
      - name: Stop Streamr Docker Stack
        if: always()
        run: |
          docker kill $(docker ps -q)
          docker rm $(docker ps -a -q)

  memory:
    if: ${{ false }}
    name: Memory Tests using Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: package-lock.json
          cache: 'npm'
          check-latest: true
      - name: bootstrap-pkg
        working-directory: './'
        run: |
          npm install -g npm@8 --prefer-offline --no-audit
          npm run bootstrap-pkg streamr-client
      - name: Start Streamr Docker Stack
        uses: streamr-dev/streamr-docker-dev-action@v1.0.0-alpha.3
        with:
          services-to-start: "mysql redis core-api cassandra parity-node0 parity-sidechain-node0 bridge nginx smtp graph-deploy-streamregistry-subgraph"
      - name: start trackers and brokers
        uses: ./.github/workflows/reusable/run-brokers-and-trackers
      - uses: nick-invision/retry@v2
        name: Run Test
        with:
          max_attempts: 2
          timeout_minutes: 20
          retry_on: error
          command: cd packages/client && npm run test-memory
      - name: Stop Streamr Docker Stack
        if: always()
        run: |
          docker kill $(docker ps -q)
          docker rm $(docker ps -a -q)
