---
# Test Build
# Any tests that need the built code should go in here.
name: Client

# Be sure to update both workflow files if you edit any env or trigger config
env:
  CI: true
  DEBUG_COLORS: true
  DEBUG: "Streamr*"
on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - '*'
concurrency:
  group: client-build-${{ github.head_ref }}
  cancel-in-progress: true
defaults:
  run:
    working-directory: packages/client
# Be sure to update both workflow files if you edit any env or trigger config

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BUNDLE_ANALYSIS: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: package-lock.json
          node-version-file: '.nvmrc'
      - name: bootstrap-pkg
        working-directory: './'
        run: |
          npm run bootstrap-pkg streamr-client
      - name: npm run build
        run: npm run build-production
      - uses: actions/upload-artifact@v2.3.1
        with:
          name: client-build
          path: packages/client/dist

  test-exports:
    name: Test Exports
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: package-lock.json
          check-latest: true
          node-version-file: '.nvmrc'
      - uses: actions/download-artifact@v2
        with:
          name: client-build
          path: packages/client/dist
      - name: bootstrap-pkg
        working-directory: './'
        run: |
          npm run bootstrap-pkg streamr-client
      - name: test-types
        run: npm run test-types
      - name: npm run test-exports
        run: npm run test-exports

  browser-realtime:
    name: Test Browser Realtime
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: package-lock.json
          node-version-file: '.nvmrc'
      - uses: actions/download-artifact@v2
        with:
          name: client-build
          path: packages/client/dist
      - name: bootstrap-pkg
        working-directory: './'
        run: |
          npm run bootstrap-pkg streamr-client
      - name: Start Streamr Docker Stack
        uses: streamr-dev/streamr-docker-dev-action@v1.0.0
        with:
          services-to-start: "init-keyspace parity-sidechain-node0 graph-deploy-streamregistry-subgraph"
      - name: start trackers and brokers
        uses: ./.github/workflows/reusable/run-brokers-and-trackers
      - name: Run Realtime Test
        working-directory: './packages/client'
        run: npm run test-browser-realtime
      - name: Stop Streamr Docker Stack
        if: always()
        run: |
          docker kill $(docker ps -q)
          docker rm $(docker ps -a -q)

  browser-resend:
    # skip to get test suite green, not sure why failing.
    name: Test Browser Resend
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: package-lock.json
          node-version-file: '.nvmrc'
      - uses: actions/download-artifact@v2
        with:
          name: client-build
          path: packages/client/dist
      - name: bootstrap-pkg
        working-directory: './'
        run: |
          npm run bootstrap-pkg streamr-client
      - name: Start Streamr Docker Stack
        uses: streamr-dev/streamr-docker-dev-action@v1.0.0
        with:
          services-to-start: "init-keyspace parity-sidechain-node0 graph-deploy-streamregistry-subgraph"
      - name: start trackers and brokers
        uses: ./.github/workflows/reusable/run-brokers-and-trackers
      - uses: nick-invision/retry@v2
        name: Run Resend Test
        with:
          max_attempts: 3
          timeout_minutes: 3
          retry_on: error
          command: cd packages/client && npm run test-browser-resend
      - name: Stop Streamr Docker Stack
        if: always()
        run: |
          docker kill $(docker ps -q)
          docker rm $(docker ps -a -q)

  benchmarks:
    name: Benchmark
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: package-lock.json
          check-latest: true
          node-version-file: '.nvmrc'
      - uses: actions/download-artifact@v2.0.10
        with:
          name: client-build
          path: packages/client/dist
      - name: Start Streamr Docker Stack
        uses: streamr-dev/streamr-docker-dev-action@v1.0.0
        with:
          services-to-start: "parity-sidechain-node0 graph-deploy-streamregistry-subgraph"
      - name: start trackers and brokers
        uses: ./.github/workflows/reusable/run-brokers-and-trackers
      - name: bootstrap-pkg
        working-directory: './'
        run: |
          npm run bootstrap-pkg streamr-client
      - name: benchmark publish
        timeout-minutes: 15
        run: DEBUG='' npm run benchmark-publish > benchmark-publish.txt
      - name: benchmark subscribe
        timeout-minutes: 15
        run: DEBUG='' npm run benchmark-subscribe > benchmark-subscribe.txt
      - name: Stop Streamr Docker Stack
        if: always()
        run: |
          docker kill $(docker ps -q)
          docker rm $(docker ps -a -q)
      - uses: actions/upload-artifact@v2.3.1
        with:
          name: client-benchmarks
          path: |
              packages/client/benchmark-publish.txt
              packages/client/benchmark-subscribe.txt
