name: Network Browser Build

on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - '*'
  schedule:
    # run every day at 00:00
    - cron: '0 0 * * *'

concurrency:
  group: network-browser-${{ github.head_ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: packages/network

jobs:
  test-browser:
    name: Test on Browser Node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.0
        with:
          cache-dependency-path: package-lock.json
          cache: 'npm'
          node-version-file: '.nvmrc'
      - name: bootstrap-pkg
        working-directory: './'
        run: |
          npm install -g npm@8 --prefer-offline --no-audit
          npm run bootstrap-pkg streamr-network
          sudo apt-get install xvfb
      - run: xvfb-run --auto-servernum npm run test-browser
        env:
          CI: true
