---
# Lint, Test and Publish
name: Protocol

on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - '*'
concurrency:
  group: protocol-build-${{ github.head_ref }}
  cancel-in-progress: true
defaults:
  run:
    working-directory: packages/protocol

jobs:
  test-unit:
    name: Lint & Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: package-lock.json
          node-version-file: '.nvmrc'
          check-latest: true

      - name: bootstrap-pkg
        working-directory: './'
        run: |
          npm run bootstrap-pkg streamr-client-protocol

      - name: eslint
        run: npm run eslint

      - name: test
        run: npm run test
