---
name: Try release broker?

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: broker-build-${{ github.head_ref }}
  cancel-in-progress: true
defaults:
  run:
    working-directory: packages/broker

jobs:
  docker-push:
    name: Build + Push Docker images
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Cache Docker layers
        uses: actions/cache@v2.1.7
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-v1-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-v1-
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          driver-opts: |
            network=host
      - uses: docker/login-action@v1.13.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: docker_meta_failure
        uses: docker/metadata-action@v3.6.2
        # if test steps failed, push sha anyway
        if: ${{ always() && (needs.test-unit.result == 'failure' || needs.test-integration.result == 'failure' || needs.test-docker.result == 'failure') }}
        with:
          images: streamr/broker-node
          tags: |
            type=sha
            type=ref,event=branch
            type=raw,value=debug
      - name: Docker meta
        id: docker_meta_success
        uses: docker/metadata-action@v3.6.2
        # if test steps succeeded
        if: ${{ always() && !(needs.test-unit.result == 'failure' || needs.test-integration.result == 'failure' || needs.test-docker.result == 'failure') }}
        with:
          images: streamr/broker-node
          tags: |
            type=sha
      - name: Setup qemu
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          driver-opts: |
            network=host
      - name: Build & Push
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          file: ./Dockerfile.broker
          platforms: linux/amd64,linux/arm64
          push: true
          load: false
          # only one of these should have tags
          tags: ${{ steps.docker_meta_success.outputs.tags }}${{ steps.docker_meta_failure.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
