name: release
on:
  workflow_run:
    branches: [main, streamr-1.0, pretestnet]
    workflows: [validate]
    types:
      - completed
jobs:
  broker-docker-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/docker-build.yml
    with:
      docker_file: Dockerfile.broker
      image_name: streamr/broker-node
      host_machine_platform: self-hosted
      build_platforms: linux/amd64,linux/arm64
      branch: ${{ github.event.workflow_run.head_branch }}
      push_image: true
    secrets:
      dockerhub_username: ${{secrets.DOCKERHUB_USERNAME}}
      dockerhub_token: ${{secrets.DOCKERHUB_TOKEN}}
