name: release
on:
  workflow_run:
    branches: [main]
    workflows: [validate]
    types:
      - completed
jobs:
  tracker-docker-image:
    uses: ./.github/workflows/docker-build.yml
    with:
      docker_file: Dockerfile.tracker
      image_name: streamr/tracker
      build_platforms: linux/amd64
      push_image: true
      test_success: ${{ github.event.workflow_run.conclusion == 'success' }}
    secrets:
      dockerhub_username: ${{secrets.DOCKERHUB_USERNAME}}
      dockerhub_token: ${{secrets.DOCKERHUB_TOKEN}}
  broker-docker-image:
    uses: ./.github/workflows/docker-build.yml
    with:
      docker_file: Dockerfile.broker
      image_name: streamr/broker-node
      build_platforms: linux/amd64,linux/arm64
      push_image: true
      test_success: ${{ github.event.workflow_run.conclusion == 'success' }}
    secrets:
      dockerhub_username: ${{secrets.DOCKERHUB_USERNAME}}
      dockerhub_token: ${{secrets.DOCKERHUB_TOKEN}}
