name: run brokers and trackers

on:
  workflow_call:

jobs:
  run_brokers_and_trackers:
    name: run brokers and trackers
    runs-on: ubuntu-latest
    steps:
      - name: start trackers and brokers
        working-directory: './packages/broker'
        run: |
          npm run build
          (cd bin && node run-all.js&)
