---
name: test-utils – Lint, Test and Publish

on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - '*'
concurrency:
  group: test-utils-build-${{ github.head_ref }}
  cancel-in-progress: true
defaults:
  run:
    working-directory: packages/test-utils

jobs:
  test-unit:
    name: Lint & Unit Test on Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json
          check-latest: true

      - name: bootstrap-pkg
        working-directory: './'
        run: |
          npm install -g npm@8 --prefer-offline --no-audit
          npm run bootstrap-pkg streamr-test-utils

      - name: eslint
        run: npm run eslint

      - name: test
        run: npm run test