name: Test Building Documentation

on:
  pull_request:
    branches: [ main ]

jobs:  
  deploy:
    name: Test building documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
          cache-dependency-path: 'package-lock.json'
      - name: Install dependencies
        run: npm run bootstrap
      - name: Build documentation
        working-directory: ./docs
        run: npm ci && npm run build && npm run refine
